apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: fcg/users-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: users-api-config
          env:
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: users-api-secret
                  key: jwt-key
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: users-api-secret
                  key: connection-string
            - name: RabbitMq__Username
              valueFrom:
                secretKeyRef:
                  name: users-api-secret
                  key: rabbitmq-username
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: users-api-secret
                  key: rabbitmq-password
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          emptyDir: {}
